DROP TABLE IF EXISTS DEPARTMENT CASCADE;
DROP TABLE IF EXISTS BRANCH CASCADE;
DROP TABLE IF EXISTS COURSE CASCADE;
DROP TABLE IF EXISTS BRANCH_COURSE CASCADE;
DROP TABLE IF EXISTS STUDENT CASCADE;
DROP TABLE IF EXISTS ENROLLS CASCADE;
